### PR TITLE
Fix FindLAME.cmake for Vcpkg

### PR DESCRIPTION
**Pull request by evpobr**

### CODE REVIEW

**Comment by evpobr** [comment]
@arthurt

**Comment by arthurt** [comment]
Just checking, is `lame_hip_library` strictly required? Does it build without it? The code doesn't use libhip, unless it's what is providing the id3_v1 genre lookup `id3tag_genre_list()`

**Comment by evpobr** [comment]
> Just checking, is `lame_hip_library` strictly required?

This dependency is optional (not in `REQUIRED_VARS` of `find_package_handle_standard_args`).

> Does it build without it?

Yes.

> The code doesn't use libhip, unless it's what is providing the id3_v1 genre lookup `id3tag_genre_list()`

It is Windows dependency, Vcpkg installs it as separate static library. It is show-stopper for me.

**Comment by arthurt** [comment]
> It is Windows dependency, Vcpkg installs it as separate static library.

Is it a required dependency? As in, can libsndfile be built with libmp3lame and without libmpghip using Vcpkg? And if so, does mp3 encoding still work?

**Comment by evpobr** [comment]
> > It is Windows dependency, Vcpkg installs it as separate static library.
> 
> Is it a required dependency? As in, can libsndfile be built with libmp3lame and without libmpghip using Vcpkg? And if so, does mp3 encoding still work?

I have linking errors without it.

**Comment by arthurt** [comment]
Unfortunetly this breaks CMake builds for me on Gentoo (and assume most other Linux distros), as libmpghip doesn't exist.

**Comment by evpobr** [comment]
> Unfortunetly this breaks CMake builds for me on Gentoo (and assume most other Linux distros), as libmpghip doesn't exist.

Hmm, it is strange.

Can you give me configure log?

**Comment by arthurt** [comment]
Looking into this, it would appear that Lame has an autotools and vc_solution, and only the vc_solution creates libmpghip. I think that this means on different platforms Lame is split into different libraries.

I'm not as familiar with CMake as perhaps I should be. Could FindLame.cmake be changed to pull in libmpghip if found but not fail if not found?

Compilation fails currently with:
```
[ 66%] Linking C shared library libsndfile.so
/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lLAME_HIP_LIBRARY-NOTFOUND
```

Something like how FindVorbis deals with VorbisEnc?

**Comment by evpobr** [comment]
@arthurt , test fix please.

**Pull request merged**
